data:
  name: "alpaca_cleaned"
  path: "yahma/alpaca-cleaned"
  batch_size: 8
  micro_batch_size: 1
  val_set_size: 200
model:
  name: 'lolcats_ar'
  pretrained_model_name_or_path: 'checkpoints/lolcats_at/best'
  max_length: 1024
  add_eos_token: False
  device_map: 'auto'
train:
  optim: 'adamw_torch'
  lr: 0.0001
  epochs: 2
  max_grad_norm: 1.0
  output_dir: 'checkpoints'
  train_qk: True
  train_qk_lora: True
  train_v: True
  train_v_lora: True
